- id: murano
  type: group
  role: [murano]
  tasks:
    - hiera
    - globals
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

- id: hiera-override
  type: puppet
  groups: ['/.*/']
  required_for: [deploy_end]
  requires: [deploy_start, hiera, netconfig, hosts]
  parameters:
    puppet_manifest: manifests/murano_hiera_override.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
